version: '3'

services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
        - .env
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - "5001:80"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:8025"
